// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Repository
{
    public partial class ParamGen
    {
        public int Id { get; set; }
        public int ParameterId { get; set; }
        public string Value { get; set; }
        public bool? Isactive { get; set; }
        public DateTime UpdateDate { get; set; }

        public virtual ParamGenList Parameter { get; set; }
    }
}